import { useState, useEffect } from 'react';
import {
  FileText,
  Download,
  Calendar,
  TrendingUp,
  TrendingDown,
  PieChart,
} from 'lucide-react';
import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
  Legend,
} from 'recharts';
import { analyticsService } from '../services/finance';
import { useTheme } from '../context/ThemeContext';
import toast from 'react-hot-toast';

const Reports = () => {
  const [loading, setLoading] = useState(true);
  const [trends, setTrends] = useState([]);
  const [selectedMonth, setSelectedMonth] = useState('');
  const [monthlyData, setMonthlyData] = useState(null);
  const { isDark } = useTheme();

  useEffect(() => {
    fetchTrends();
  }, []);

  const fetchTrends = async () => {
    try {
      setLoading(true);
      const response = await analyticsService.getTrends(12);
      setTrends(response.data.trends);
      
      if (response.data.trends.length > 0) {
        const latest = response.data.trends[response.data.trends.length - 1];
        setSelectedMonth(latest.month);
        setMonthlyData(latest);
      }
    } catch (error) {
      toast.error('Failed to load report data');
    } finally {
      setLoading(false);
    }
  };

  const handleMonthChange = (month) => {
    setSelectedMonth(month);
    const data = trends.find((t) => t.month === month);
    setMonthlyData(data);
  };

  const generatePDFReport = () => {
    // Create a simple text-based report
    if (!monthlyData) {
      toast.error('No data to export');
      return;
    }

    const reportContent = `
FINSENSE FINANCIAL REPORT
${monthlyData.monthName}
==========================

SUMMARY
-------
Total Income:   $${monthlyData.income.toLocaleString()}
Total Expenses: $${monthlyData.expense.toLocaleString()}
Net Savings:    $${monthlyData.savings.toLocaleString()}
Savings Rate:   ${monthlyData.income > 0 ? Math.round((monthlyData.savings / monthlyData.income) * 100) : 0}%

MONTHLY TRENDS (Last 6 Months)
------------------------------
${trends.slice(-6).map(t => 
  `${t.monthName}: Income $${t.income.toLocaleString()} | Expenses $${t.expense.toLocaleString()} | Savings $${t.savings.toLocaleString()}`
).join('\n')}

Generated by FinSense - AI-Powered Financial Tracking
Report Date: ${new Date().toLocaleDateString()}
    `.trim();

    // Create and download the file
    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `finsense-report-${selectedMonth}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    toast.success('Report downloaded!');
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center h-64">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary-500"></div>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <h2 className="text-2xl font-bold text-gray-800 dark:text-white">Financial Reports</h2>
          <p className="text-gray-500 dark:text-gray-400">Review your financial history and trends</p>
        </div>
        <button
          onClick={generatePDFReport}
          className="flex items-center gap-2 px-4 py-2.5 bg-primary-500 text-white rounded-xl hover:bg-primary-600 transition font-medium"
        >
          <Download className="w-5 h-5" />
          Download Report
        </button>
      </div>

      {/* Month Selector */}
      <div className="bg-white dark:bg-dark-800 rounded-2xl border border-gray-200 dark:border-dark-700 p-6">
        <div className="flex items-center gap-2 mb-4">
          <Calendar className="w-5 h-5 text-gray-500 dark:text-gray-400" />
          <h3 className="text-lg font-semibold text-gray-800 dark:text-white">Select Month</h3>
        </div>
        <div className="flex flex-wrap gap-2">
          {trends.map((trend) => (
            <button
              key={trend.month}
              onClick={() => handleMonthChange(trend.month)}
              className={`px-4 py-2 rounded-xl transition font-medium ${
                selectedMonth === trend.month
                  ? 'bg-primary-500 text-white'
                  : 'bg-gray-100 dark:bg-dark-700 text-gray-700 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-dark-600'
              }`}
            >
              {trend.monthName}
            </button>
          ))}
        </div>
      </div>

      {/* Monthly Summary */}
      {monthlyData && (
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          <div className="bg-white dark:bg-dark-800 rounded-2xl border border-gray-200 dark:border-dark-700 p-6">
            <div className="flex items-center gap-3">
              <div className="w-12 h-12 bg-green-500/10 rounded-xl flex items-center justify-center">
                <TrendingUp className="w-6 h-6 text-green-500" />
              </div>
              <div>
                <p className="text-sm text-gray-500 dark:text-gray-400">Total Income</p>
                <p className="text-2xl font-bold text-gray-800 dark:text-white">
                  ${monthlyData.income.toLocaleString()}
                </p>
              </div>
            </div>
          </div>

          <div className="bg-white dark:bg-dark-800 rounded-2xl border border-gray-200 dark:border-dark-700 p-6">
            <div className="flex items-center gap-3">
              <div className="w-12 h-12 bg-red-500/10 rounded-xl flex items-center justify-center">
                <TrendingDown className="w-6 h-6 text-red-500" />
              </div>
              <div>
                <p className="text-sm text-gray-500 dark:text-gray-400">Total Expenses</p>
                <p className="text-2xl font-bold text-gray-800 dark:text-white">
                  ${monthlyData.expense.toLocaleString()}
                </p>
              </div>
            </div>
          </div>

          <div className="bg-white dark:bg-dark-800 rounded-2xl border border-gray-200 dark:border-dark-700 p-6">
            <div className="flex items-center gap-3">
              <div className={`w-12 h-12 rounded-xl flex items-center justify-center ${
                monthlyData.savings >= 0 ? 'bg-primary-500/10' : 'bg-red-500/10'
              }`}>
                <PieChart className={`w-6 h-6 ${
                  monthlyData.savings >= 0 ? 'text-primary-500' : 'text-red-500'
                }`} />
              </div>
              <div>
                <p className="text-sm text-gray-500 dark:text-gray-400">Net Savings</p>
                <p className={`text-2xl font-bold ${
                  monthlyData.savings >= 0 ? 'text-gray-800 dark:text-white' : 'text-red-500'
                }`}>
                  ${monthlyData.savings.toLocaleString()}
                </p>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Trends Chart */}
      <div className="bg-white dark:bg-dark-800 rounded-2xl border border-gray-200 dark:border-dark-700 p-6">
        <div className="flex items-center gap-2 mb-6">
          <FileText className="w-5 h-5 text-gray-500 dark:text-gray-400" />
          <h3 className="text-lg font-semibold text-gray-800 dark:text-white">Income vs Expenses Trend</h3>
        </div>
        
        <ResponsiveContainer width="100%" height={400}>
          <BarChart data={trends}>
            <CartesianGrid strokeDasharray="3 3" stroke={isDark ? '#252f4a' : '#f1f5f9'} />
            <XAxis dataKey="monthName" stroke={isDark ? '#9ca3af' : '#64748b'} fontSize={12} />
            <YAxis stroke={isDark ? '#9ca3af' : '#64748b'} fontSize={12} />
            <Tooltip
              contentStyle={{
                backgroundColor: isDark ? '#1a2236' : '#fff',
                border: `1px solid ${isDark ? '#252f4a' : '#e2e8f0'}`,
                borderRadius: '12px',
                color: isDark ? '#fff' : '#000',
              }}
              formatter={(value) => [`$${value.toLocaleString()}`, '']}
            />
            <Legend />
            <Bar dataKey="income" name="Income" fill="#22c55e" radius={[6, 6, 0, 0]} />
            <Bar dataKey="expense" name="Expenses" fill="#ef4444" radius={[6, 6, 0, 0]} />
          </BarChart>
        </ResponsiveContainer>
      </div>

      {/* Savings Trend */}
      <div className="bg-white dark:bg-dark-800 rounded-2xl border border-gray-200 dark:border-dark-700 p-6">
        <h3 className="text-lg font-semibold text-gray-800 dark:text-white mb-6">Monthly Savings</h3>
        <div className="overflow-x-auto">
          <table className="w-full">
            <thead>
              <tr className="border-b border-gray-200 dark:border-dark-700">
                <th className="text-left py-3 px-4 text-sm font-medium text-gray-500 dark:text-gray-400">Month</th>
                <th className="text-right py-3 px-4 text-sm font-medium text-gray-500 dark:text-gray-400">Income</th>
                <th className="text-right py-3 px-4 text-sm font-medium text-gray-500 dark:text-gray-400">Expenses</th>
                <th className="text-right py-3 px-4 text-sm font-medium text-gray-500 dark:text-gray-400">Savings</th>
                <th className="text-right py-3 px-4 text-sm font-medium text-gray-500 dark:text-gray-400">Rate</th>
              </tr>
            </thead>
            <tbody>
              {trends.slice().reverse().map((trend) => (
                <tr key={trend.month} className="border-b border-gray-200 dark:border-dark-700 hover:bg-gray-50 dark:hover:bg-dark-700/50 transition">
                  <td className="py-3 px-4 font-medium text-gray-800 dark:text-white">{trend.monthName}</td>
                  <td className="py-3 px-4 text-right text-green-500">
                    ${trend.income.toLocaleString()}
                  </td>
                  <td className="py-3 px-4 text-right text-red-500">
                    ${trend.expense.toLocaleString()}
                  </td>
                  <td className={`py-3 px-4 text-right font-medium ${
                    trend.savings >= 0 ? 'text-primary-500' : 'text-red-500'
                  }`}>
                    ${trend.savings.toLocaleString()}
                  </td>
                  <td className="py-3 px-4 text-right">
                    <span className={`px-2 py-1 rounded-full text-xs font-medium ${
                      trend.income > 0 && (trend.savings / trend.income) >= 0.2
                        ? 'bg-green-500/10 text-green-500'
                        : trend.income > 0 && (trend.savings / trend.income) >= 0
                        ? 'bg-yellow-500/10 text-yellow-500'
                        : 'bg-red-500/10 text-red-500'
                    }`}>
                      {trend.income > 0
                        ? `${Math.round((trend.savings / trend.income) * 100)}%`
                        : '0%'}
                    </span>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};

export default Reports;
