import { useState, useEffect } from 'react';
import {
  Download,
  Calendar,
  TrendingUp,
  TrendingDown,
  PieChart,
  ChevronLeft,
  ChevronRight,
  X,
} from 'lucide-react';
import {
  AreaChart,
  Area,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
} from 'recharts';
import { analyticsService, transactionService } from '../services/finance';
import { useTheme } from '../context/ThemeContext';
import toast from 'react-hot-toast';

const MONTHS = [
  'January', 'February', 'March', 'April', 'May', 'June',
  'July', 'August', 'September', 'October', 'November', 'December'
];

const Reports = () => {
  const [loading, setLoading] = useState(true);
  const [selectedDate, setSelectedDate] = useState(new Date());
  const [monthlyData, setMonthlyData] = useState(null);
  const [transactions, setTransactions] = useState([]);
  const [yearTrends, setYearTrends] = useState([]);
  const [showCalendar, setShowCalendar] = useState(false);
  const [calendarYear, setCalendarYear] = useState(new Date().getFullYear());
  const { isDark } = useTheme();

  useEffect(() => {
    fetchMonthData();
  }, [selectedDate]);

  const fetchMonthData = async () => {
    try {
      setLoading(true);
      
      const year = selectedDate.getFullYear();
      const month = selectedDate.getMonth();
      const startDate = new Date(year, month, 1).toISOString();
      const endDate = new Date(year, month + 1, 0, 23, 59, 59).toISOString();
      
      // Fetch trends for the year and transactions for the selected month
      const [trendsRes, transactionsRes] = await Promise.all([
        analyticsService.getTrends(12),
        transactionService.getAll({ 
          startDate: startDate.split('T')[0], 
          endDate: endDate.split('T')[0],
          limit: 100 
        }),
      ]);

      const trends = trendsRes.data.trends;
      setYearTrends(trends.filter(t => t.income > 0 || t.expense > 0));
      
      // Find data for selected month
      const monthKey = `${year}-${String(month + 1).padStart(2, '0')}`;
      const selectedMonthData = trends.find(t => t.month === monthKey);
      
      if (selectedMonthData) {
        setMonthlyData(selectedMonthData);
      } else {
        // Calculate from transactions if not in trends
        const txns = transactionsRes.data.transactions || [];
        let income = 0, expense = 0;
        txns.forEach(t => {
          if (t.type === 'INCOME') income += parseFloat(t.amount);
          else expense += parseFloat(t.amount);
        });
        setMonthlyData({
          month: monthKey,
          monthName: `${MONTHS[month]} ${year}`,
          income,
          expense,
          savings: income - expense,
        });
      }
      
      setTransactions(transactionsRes.data.transactions || []);
    } catch (error) {
      toast.error('Failed to load history data');
      console.error(error);
    } finally {
      setLoading(false);
    }
  };

  const handleMonthSelect = (month) => {
    const newDate = new Date(calendarYear, month, 1);
    setSelectedDate(newDate);
    setShowCalendar(false);
  };

  const generatePDFReport = () => {
    if (!monthlyData) {
      toast.error('No data to export');
      return;
    }

    const reportContent = `
FINSENSE FINANCIAL REPORT
${monthlyData.monthName}
==========================

SUMMARY
-------
Total Income:   $${monthlyData.income.toLocaleString()}
Total Expenses: $${monthlyData.expense.toLocaleString()}
Net Savings:    $${monthlyData.savings.toLocaleString()}
Savings Rate:   ${monthlyData.income > 0 ? Math.round((monthlyData.savings / monthlyData.income) * 100) : 0}%

TRANSACTIONS
------------
${transactions.map(t => 
  `${new Date(t.date).toLocaleDateString()} | ${t.type} | ${t.category} | $${parseFloat(t.amount).toLocaleString()}`
).join('\n')}

Generated by FinSense - AI-Powered Financial Tracking
Report Date: ${new Date().toLocaleDateString()}
    `.trim();

    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `finsense-report-${selectedDate.getFullYear()}-${String(selectedDate.getMonth() + 1).padStart(2, '0')}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    toast.success('Report downloaded!');
  };

  const selectedMonthName = `${MONTHS[selectedDate.getMonth()]} ${selectedDate.getFullYear()}`;

  if (loading) {
    return (
      <div className="flex items-center justify-center h-64">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary-500"></div>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <h2 className="text-2xl font-bold text-gray-800 dark:text-white">Financial History</h2>
          <p className="text-gray-500 dark:text-gray-400">Review your financial history and trends</p>
        </div>
        <button
          onClick={generatePDFReport}
          disabled={!monthlyData || (monthlyData.income === 0 && monthlyData.expense === 0)}
          className="flex items-center gap-2 px-4 py-2.5 bg-primary-500 text-white rounded-xl hover:bg-primary-600 transition font-medium disabled:opacity-50 disabled:cursor-not-allowed"
        >
          <Download className="w-5 h-5" />
          Download Report
        </button>
      </div>

      {/* Month Picker */}
      <div className="bg-white dark:bg-dark-800 rounded-2xl border border-gray-200 dark:border-dark-700 p-6">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-3">
            <Calendar className="w-5 h-5 text-primary-500" />
            <span className="text-gray-600 dark:text-gray-400">Viewing:</span>
          </div>
          <div className="relative">
            <button
              onClick={() => setShowCalendar(!showCalendar)}
              className="flex items-center gap-2 px-4 py-2.5 bg-primary-500 text-white rounded-xl hover:bg-primary-600 transition font-medium"
            >
              <Calendar className="w-4 h-4" />
              {selectedMonthName}
            </button>

            {/* Calendar Dropdown */}
            {showCalendar && (
              <>
                <div className="fixed inset-0 z-40" onClick={() => setShowCalendar(false)} />
                <div className={`absolute right-0 top-full mt-2 z-50 w-72 rounded-2xl shadow-xl border ${
                  isDark ? 'bg-dark-800 border-dark-700' : 'bg-white border-gray-200'
                } p-4`}>
                  {/* Year Navigation */}
                  <div className="flex items-center justify-between mb-4">
                    <button
                      onClick={() => setCalendarYear(calendarYear - 1)}
                      className="p-2 hover:bg-gray-100 dark:hover:bg-dark-700 rounded-lg transition"
                    >
                      <ChevronLeft className="w-5 h-5 text-gray-600 dark:text-gray-400" />
                    </button>
                    <span className="text-lg font-semibold text-gray-800 dark:text-white">
                      {calendarYear}
                    </span>
                    <button
                      onClick={() => setCalendarYear(calendarYear + 1)}
                      className="p-2 hover:bg-gray-100 dark:hover:bg-dark-700 rounded-lg transition"
                    >
                      <ChevronRight className="w-5 h-5 text-gray-600 dark:text-gray-400" />
                    </button>
                  </div>

                  {/* Month Grid */}
                  <div className="grid grid-cols-3 gap-2">
                    {MONTHS.map((month, index) => {
                      const isSelected = selectedDate.getMonth() === index && selectedDate.getFullYear() === calendarYear;
                      const isFuture = new Date(calendarYear, index, 1) > new Date();
                      
                      return (
                        <button
                          key={month}
                          onClick={() => !isFuture && handleMonthSelect(index)}
                          disabled={isFuture}
                          className={`py-2 px-3 rounded-xl text-sm font-medium transition ${
                            isSelected
                              ? 'bg-primary-500 text-white'
                              : isFuture
                              ? 'text-gray-300 dark:text-gray-600 cursor-not-allowed'
                              : 'hover:bg-gray-100 dark:hover:bg-dark-700 text-gray-700 dark:text-gray-300'
                          }`}
                        >
                          {month.slice(0, 3)}
                        </button>
                      );
                    })}
                  </div>
                </div>
              </>
            )}
          </div>
        </div>
      </div>

      {/* Monthly Summary Cards */}
      {monthlyData && (monthlyData.income > 0 || monthlyData.expense > 0) ? (
        <>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            <div className="bg-white dark:bg-dark-800 rounded-2xl border border-gray-200 dark:border-dark-700 p-6">
              <div className="flex items-center gap-3">
                <div className="w-12 h-12 bg-green-500/10 rounded-xl flex items-center justify-center">
                  <TrendingUp className="w-6 h-6 text-green-500" />
                </div>
                <div>
                  <p className="text-sm text-gray-500 dark:text-gray-400">Total Income</p>
                  <p className="text-2xl font-bold text-gray-800 dark:text-white">
                    ${monthlyData.income.toLocaleString()}
                  </p>
                </div>
              </div>
            </div>

            <div className="bg-white dark:bg-dark-800 rounded-2xl border border-gray-200 dark:border-dark-700 p-6">
              <div className="flex items-center gap-3">
                <div className="w-12 h-12 bg-red-500/10 rounded-xl flex items-center justify-center">
                  <TrendingDown className="w-6 h-6 text-red-500" />
                </div>
                <div>
                  <p className="text-sm text-gray-500 dark:text-gray-400">Total Expenses</p>
                  <p className="text-2xl font-bold text-gray-800 dark:text-white">
                    ${monthlyData.expense.toLocaleString()}
                  </p>
                </div>
              </div>
            </div>

            <div className="bg-white dark:bg-dark-800 rounded-2xl border border-gray-200 dark:border-dark-700 p-6">
              <div className="flex items-center gap-3">
                <div className={`w-12 h-12 rounded-xl flex items-center justify-center ${
                  monthlyData.savings >= 0 ? 'bg-primary-500/10' : 'bg-red-500/10'
                }`}>
                  <PieChart className={`w-6 h-6 ${
                    monthlyData.savings >= 0 ? 'text-primary-500' : 'text-red-500'
                  }`} />
                </div>
                <div>
                  <p className="text-sm text-gray-500 dark:text-gray-400">Net Savings</p>
                  <p className={`text-2xl font-bold ${
                    monthlyData.savings >= 0 ? 'text-gray-800 dark:text-white' : 'text-red-500'
                  }`}>
                    ${Math.abs(monthlyData.savings).toLocaleString()}
                    {monthlyData.savings < 0 && <span className="text-sm ml-1">(deficit)</span>}
                  </p>
                </div>
              </div>
            </div>
          </div>

          {/* Transactions Table */}
          {transactions.length > 0 && (
            <div className="bg-white dark:bg-dark-800 rounded-2xl border border-gray-200 dark:border-dark-700 p-6">
              <h3 className="text-lg font-semibold text-gray-800 dark:text-white mb-4">
                Transactions in {selectedMonthName}
              </h3>
              <div className="overflow-x-auto">
                <table className="w-full">
                  <thead>
                    <tr className="border-b border-gray-200 dark:border-dark-700">
                      <th className="text-left py-3 px-4 text-sm font-medium text-gray-500 dark:text-gray-400">Date</th>
                      <th className="text-left py-3 px-4 text-sm font-medium text-gray-500 dark:text-gray-400">Category</th>
                      <th className="text-left py-3 px-4 text-sm font-medium text-gray-500 dark:text-gray-400">Type</th>
                      <th className="text-right py-3 px-4 text-sm font-medium text-gray-500 dark:text-gray-400">Amount</th>
                    </tr>
                  </thead>
                  <tbody>
                    {transactions.map((t) => (
                      <tr key={t.id} className="border-b border-gray-200 dark:border-dark-700 hover:bg-gray-50 dark:hover:bg-dark-700/50 transition">
                        <td className="py-3 px-4 text-gray-700 dark:text-gray-300">
                          {new Date(t.date).toLocaleDateString()}
                        </td>
                        <td className="py-3 px-4 font-medium text-gray-800 dark:text-white">
                          {t.category}
                        </td>
                        <td className="py-3 px-4">
                          <span className={`px-2 py-1 rounded-full text-xs font-medium ${
                            t.type === 'INCOME'
                              ? 'bg-green-500/10 text-green-500'
                              : 'bg-red-500/10 text-red-500'
                          }`}>
                            {t.type}
                          </span>
                        </td>
                        <td className={`py-3 px-4 text-right font-medium ${
                          t.type === 'INCOME' ? 'text-green-500' : 'text-red-500'
                        }`}>
                          {t.type === 'INCOME' ? '+' : '-'}${parseFloat(t.amount).toLocaleString()}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          )}

          {/* Year Trend Chart */}
          {yearTrends.length > 1 && (
            <div className="bg-white dark:bg-dark-800 rounded-2xl border border-gray-200 dark:border-dark-700 p-6">
              <h3 className="text-lg font-semibold text-gray-800 dark:text-white mb-6">
                Income vs Expenses Trend
              </h3>
              <ResponsiveContainer width="100%" height={300}>
                <AreaChart data={yearTrends}>
                  <defs>
                    <linearGradient id="incomeGradient" x1="0" y1="0" x2="0" y2="1">
                      <stop offset="5%" stopColor="#22c55e" stopOpacity={0.3} />
                      <stop offset="95%" stopColor="#22c55e" stopOpacity={0} />
                    </linearGradient>
                    <linearGradient id="expenseGradient" x1="0" y1="0" x2="0" y2="1">
                      <stop offset="5%" stopColor="#ef4444" stopOpacity={0.3} />
                      <stop offset="95%" stopColor="#ef4444" stopOpacity={0} />
                    </linearGradient>
                  </defs>
                  <CartesianGrid strokeDasharray="3 3" stroke={isDark ? '#252f4a' : '#f1f5f9'} />
                  <XAxis 
                    dataKey="monthName" 
                    stroke={isDark ? '#9ca3af' : '#64748b'} 
                    fontSize={12}
                    tickFormatter={(value) => value.split(' ')[0].slice(0, 3)}
                  />
                  <YAxis stroke={isDark ? '#9ca3af' : '#64748b'} fontSize={12} />
                  <Tooltip
                    contentStyle={{
                      backgroundColor: isDark ? '#1a2236' : '#fff',
                      border: `1px solid ${isDark ? '#252f4a' : '#e2e8f0'}`,
                      borderRadius: '12px',
                      color: isDark ? '#fff' : '#000',
                    }}
                    formatter={(value) => [`$${value.toLocaleString()}`, '']}
                  />
                  <Area 
                    type="monotone" 
                    dataKey="income" 
                    name="Income"
                    stroke="#22c55e" 
                    strokeWidth={2}
                    fill="url(#incomeGradient)" 
                  />
                  <Area 
                    type="monotone" 
                    dataKey="expense" 
                    name="Expenses"
                    stroke="#ef4444" 
                    strokeWidth={2}
                    fill="url(#expenseGradient)" 
                  />
                </AreaChart>
              </ResponsiveContainer>
              
              {/* Legend */}
              <div className="flex justify-center gap-6 mt-4">
                <div className="flex items-center gap-2">
                  <div className="w-3 h-3 rounded-full bg-green-500" />
                  <span className="text-sm text-gray-600 dark:text-gray-400">Income</span>
                </div>
                <div className="flex items-center gap-2">
                  <div className="w-3 h-3 rounded-full bg-red-500" />
                  <span className="text-sm text-gray-600 dark:text-gray-400">Expenses</span>
                </div>
              </div>
            </div>
          )}
        </>
      ) : (
        <div className="bg-white dark:bg-dark-800 rounded-2xl border border-gray-200 dark:border-dark-700 p-12 text-center">
          <div className="w-16 h-16 mx-auto mb-4 bg-gray-100 dark:bg-dark-700 rounded-full flex items-center justify-center">
            <Calendar className="w-8 h-8 text-gray-400" />
          </div>
          <h3 className="text-lg font-semibold text-gray-800 dark:text-white mb-2">
            No data for {selectedMonthName}
          </h3>
          <p className="text-gray-500 dark:text-gray-400">
            There are no transactions recorded for this month. Select a different month or add transactions.
          </p>
        </div>
      )}
    </div>
  );
};

export default Reports;
